### PR TITLE
Changed the Google Cloud Storage API version to v1. Previous beta ones w...

### PR DESCRIPTION
**Pull request by erans**
...on't work

### CODE REVIEW

**Comment by edwardchuang** [comment]
Bump. This pull request does fix the problem of uploading data onto GCS instead of silent discard.

**Comment by erans** [comment]
Will you merge it? It seems I do not appear in the Contributors file or something like that and that is the main reason why it won't let you merge it (I think).

**Comment by markwalkom** [comment]
G'Day @erans,
It seems like you haven't signed the CLA, we cannot accept a PR unless you have signed this as it's there to protect all parties, including yourself.

You can find details of that here - https://github.com/elastic/logstash/blob/master/CONTRIBUTING.md#contribution-steps

**Comment by erans** [comment]
I've signed it.

**Comment by jsvd** [comment]
LGTM

**Pull request closed without merging**
